# permissions for end users to view dataservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dataservice-viewer-role
rules:
- apiGroups:
  - d3os-product.com.d3os
  resources:
  - dataservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - d3os-product.com.d3os
  resources:
  - dataservices/status
  verbs:
  - get
