
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - d3os-product.com.d3os
  resources:
  - dataservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - d3os-product.com.d3os
  resources:
  - dataservices/finalizers
  verbs:
  - update
- apiGroups:
  - d3os-product.com.d3os
  resources:
  - dataservices/status
  verbs:
  - get
  - patch
  - update
