apiVersion: d3os-product.com.d3os/v1
kind: DataService
metadata:
  name: dataservice-sample
spec:
  mysql:
    name: mysql-dataservice
    kind: 1
    thirdParty:
  uuc:
    name: uuc
    kind: 3
    thirdParty:
      checkCMD: 'curl --output /dev/null --silent --head --fail https://id.cosmoplat.com/duc'
      url: https://id.cosmoplat.com/duc
  eureka:
    name: eureka
    kind: 0
    thirdParty:
  api-manager:
    image: registry-edge.cosmoplat.com/dataservice/api-manager:v1.4
    name: api-manager
    nodePort:
    port: 9085
    replica: 1
    env:
      writer: "draven"
  auth:
    image: registry-edge.cosmoplat.com/dataservice/auth:v1.4
    name: auth
    nodePort:
    port: 9081
    replica: 1
  ds-adapter:
    image: registry-edge.cosmoplat.com/dataservice/ds-adapter:v1.4
    name: ds-adapter
    nodePort:
    port: 9086
    replica: 1
  es-adapter:
    image: registry-edge.cosmoplat.com/dataservice/es-adapter:v1.4
    name: es-adapter
    nodePort:
    port: 9087
    replica: 1
  gateway-master:
    image: registry-edge.cosmoplat.com/dataservice/gateway-master:v1.4
    name: gateway-master
    nodePort:
    port: 9184
    replica: 1
  gateway-web:
    image: registry-edge.cosmoplat.com/dataservice/gateway-web:v1.4
    name: gateway-web
    nodePort:
    port: 9084
    replica: 1
  proxy:
    image: registry-edge.cosmoplat.com/dataservice/proxy:v1.4
    name: proxy
    nodePort:
    port: 9094
    replica: 1
  trd-adapter:
    image: registry-edge.cosmoplat.com/dataservice/trd-adapter:v1.4
    name: trd-adapter
    nodePort:
    port: 9088
    replica: 1
  web:
    image: registry-edge.cosmoplat.com/dataservice/dataservice-web:v1.4
    name: web
    nodePort: 30180
    port: 80
    replica: 1
